### ISSUE TITLE
Mozilla EV tool not working

### ISSUE THREAD

**Issue by jschlyter** [kirei/catt#12]
extract-mozilla-ev.py seems to be not functioning, could you please take a look?

**Comment by secworks** [comment]
Sure, I'll look and fix.

**Comment by secworks** [comment]
it seems that the moz source has been moved into a new repo:
https://mxr.mozilla.org/mozilla-central/source/security/certverifier/ExtendedValidation.cpp?raw=1

But reading that site seems to suggest that one should not use DXR either, but use Moz repos on Github. Googling ended up pointing to Moz-Gecko. And indeed there is a similar file there:
https://raw.githubusercontent.com/mozilla/gecko-dev/master/security/certverifier/ExtendedValidation.cpp

Similar being the operating word. The moz parser can read the file, but the results is incorrect.

**Comment by secworks** [comment]
I just committed a fix in c7863089236caef2e843edb25580d44f0c069556. It seems to work, but please check that it really does.

**Comment by jschlyter** [comment]
How come the fingerprints are 42 nibbles, should it be 40?

**Comment by secworks** [comment]
No should be 64 nibbles. The new source code parsed have the fingerprint byte values on three lines, not two. Could probably be parsed in a more robust way. There is a fix in https://github.com/kirei/catt/commit/3cd323bfd5ba3201f2c66c2d4492302fa267c2ac.

**Comment by secworks** [comment]
We can probably close this issue.
